name: jlk_app
description: A comprehensive career guide for young african girls.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  file_picker: ^8.1.3
  firebase_storage: ^12.3.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.0
  dio: ^5.7.0
  google_generative_ai: ^0.4.6
  firebase_vertexai: ^1.0.2
  http: ^1.2.2

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true 
  remove_alpha_ios: true
  image_path: "assets/images/jlk_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/jlk_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
