name: jlk_app
description: A comprehensive career guide for young african girls.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  english_words: ^4.0.0
  flutter_lorem: ^2.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
